services:
  classifier:
    model_path: 'weights/model.pt'
    device: ${oc.env:POSTER_DEVICE,'cpu'}
    classes: ['agriculture',
              'artisinal_mine',
              'bare_ground',
              'blooming',
              'blow_down',
              'clear',
              'cloudy',
              'conventional_mine',
              'cultivation',
              'habitation',
              'haze',
              'partly_cloudy',
              'primary',
              'road',
              'selective_logging',
              'slash_burn',
              'water']
    size: 224
    thresholds: 0.3

